---
- name: Linux Update with Ansible
  hosts: all
  tasks:
    # This task updates servers that use 'yum' and RPM packages
    # by looking for CentOS or RedHat as a distribution name. This
    # will may also pick up modern OracleLinux but OL has a lot of
    # different strings.
    - name: .rpm upgrade server
      yum: >
        update_cache=yes
        name=*
        state=latest
        update_cache=yes
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'
        or
        ansible_distribution == 'Fedora'

    # This task updates servers that use 'apt' and DEB packages
    # by looking for Debian or Ubuntu as a distribution name.
    - name: .deb do dist-upgrade
      apt: >
        update_cache=yes
        cache_valid_time=1200
        upgrade=dist
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'
