---
- name: Linux Update with Ansible
  hosts: all
  tasks:
    # This task updates servers that use 'yum' and RPM packages
    # by looking for CentOS or RedHat as a distribution name. This
    # will may also pick up modern OracleLinux but OL has a lot of
    # different strings.
    - name: .rpm upgrade server
      ansible.builtin.yum:
        name: "*"
        update_cache: "yes"
        state: latest
        cmd: ""
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'
        or
        ansible_distribution == 'Fedora'

    # This task updates servers that use 'apt' and DEB packages
    # by looking for Debian or Ubuntu as a distribution name.
    - name: .deb do dist-upgrade
      ansible.builtin.apt:
        update_cache: "yes"
        cache_valid_time: "1200"
        upgrade: "dist\n"
        cmd: ""
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'

    - name: Clean YUM Cache
      ansible.builtin.command: yum clean all
      when: >
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'
        or
        ansible_distribution == 'Fedora'

    - name: Clean APT chache
      ansible.builtin.command: apt clean all
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'
